export const paths = {
  home: '/',
  token: 'https://shape.network/token',
  shape: 'https://shape.network',
  canonical: 'https://docs.shape.network',
  repo: 'https://github.com/shape-network/docs',
  repoBase: 'https://github.com/shape-network/docs/tree/main/',
  twitter: 'https://x.com/shape',
  discord: 'https://discord.com/invite/shape-l2',
  gasback: 'https://docs.shape.network/gasback',
  stack: 'https://stack.shape.network',
  alchemyNode: 'https://www.alchemy.com/supernode',
  alchemyDashboard: 'https://www.alchemy.com/dashboard',
  moveableType: 'https://moveabletype.deafbeef.com',
  retroPGF: 'https://app.optimism.io/retropgf',
  deployForFree: 'https://docs.optimism.io/builders/app-developers/tutorials/deploy-for-free',
  opConsole: 'https://console.optimism.io/',
};
